version: '3'

services:

  postgres:
    image: postgres:10-alpine
    ports:
    - "5432:5432"
    volumes:
    - ${POSTGRES_VOLUME:-postgres-volume}:/var/lib/postgresql/data
    environment:
    - POSTGRES_DB=${POSTGRES_DB}
    - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    - POSTGRES_USER=${POSTGRES_USER}

  concourse:
    image: concourse/concourse
    command: quickstart
    privileged: true
    depends_on:
    - postgres
    ports:
    - "8080:8080"
    environment:
    - CONCOURSE_POSTGRES_HOST=postgres
    - CONCOURSE_POSTGRES_USER=${POSTGRES_USER}
    - CONCOURSE_POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    - CONCOURSE_POSTGRES_DATABASE=${POSTGRES_DB}
    - CONCOURSE_EXTERNAL_URL=http://localhost:8080
    - CONCOURSE_ADD_LOCAL_USER=${CONCOURSE_LOCAL_USER}
    - CONCOURSE_MAIN_TEAM_LOCAL_USER=${CONCOURSE_LOCAL_TEAM}
    - CONCOURSE_WORKER_BAGGAGECLAIM_DRIVER=overlay
    - CONCOURSE_CLIENT_SECRET=Y29uY291cnNlLXdlYgo=
    - CONCOURSE_TSA_CLIENT_SECRET=Y29uY291cnNlLXdvcmtlcgo=

volumes:
  postgres-volume:
